### PR TITLE
Hello microverse

### PR DESCRIPTION
**Pull request by Mutai-Gilbert**
This is a simple html and css project

### CODE REVIEW

**Comment by Mutai-Gilbert** [comment]
This is a simple html and css project on Day 2 Microverse

**Review by mckent05 — CHANGES_REQUESTED** [review]
Hi @Mutai-Gilbert , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
almost there

## Please note that you are not required to open another pull request for your next review.

## Highlights
- Project is set up correctly ✔️ 
- GitHub flow is used correctly 💯 💯 
- Linter checks are passing ✔️ ✔️ 


## Required Changes ♻️
- Just like the previous reviewer suggested please update your readme file. Having a professional readme helps to make your repo look more professional.

## Optional suggestions
**[OPTIONAL]** - In your future projects, please use more descriptive commit messages that summarises what you did during that commit.😄 😄 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by vickymarz — CHANGES_REQUESTED** [review]
Hi @Mutai-Gilbert, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As the previous reviewer has earlier suggested, I think it should be better if you make more information in your README file, the README file should be descriptive. You should use this microverse [template](https://github.com/microverseinc/readme-template/blob/master/README.md) and put all necessary information 🙃 🙃

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sajid-munawar — CHANGES_REQUESTED** [review]
> # Changes Required 
 ### Hi @Mutai-Gilbert ,
 Nice job, you are almost there.
 
 
 
 ## (Highlights) Good Points: 
 * Followed Github flow :heavy_check_mark:
 * Great PR Summary description :heavy_check_mark: 
 ## (Changes Required) Aspects to improve: 
 *  ### Please do the following:


- [ ] As the prevoues reviewers mentioned kindly add a [README](https://github.com/microverseinc/readme-template) file to your repo, using the Microverse [template](https://github.com/microverseinc/readme-template) as this will give users detailed information about your project. Here is demo below

https://user-images.githubusercontent.com/52934128/176309876-98f49c4e-3e62-4edd-9bf3-51a66f48e2cd.mp4


 ## [Optional] suggestions:
 * Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 **Cheers and Happy coding! :clap::clap::clap:**
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear
 Please, remember to tag @topeogunleye in your question so I can receive the notification.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by jerryowusu — CHANGES_REQUESTED** [review]
Hi @Mutai-Gilbert , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, and it can be very frustrating when you know you have done all you could but still need to push on. Do not lose hope, you are almost there. You just need to make a few changes.

almost there


 ## Highlights

- [ ] All linters passing :heavy_check_mark: 
- [ ] Excellent GitHub flow :heavy_check_mark: 
- [ ] Project set up correctly

 ## Required Changes ♻️

- [ ] There is still problem with the readme file. I can see you are making the required effort to update it as requested by the previous reviewers, but the changes are being done in the main branch (as shown below). However since you are submitting the 'hello-microverse' branch for the review, it is better to make all the changes in that branch. 
Screenshot from 2022-09-20 19-12-16

- [ ] As stated above, kindly make all changes in the 'hello-microverse' branch instead of the main branch. In addition, please ensure that you edit the readme file to suit the project you are working on. You can check [this](https://github.com/jerryowusu/personal-portfolio/edit/main/README.md) for inspiration.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ha-manel — APPROVED** [review]
# STATUS: APPROVED ✅
## Hi @Mutai-Gilbert 👋

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

 

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
